[theme]
base = "dark"
primaryColor = "#FFD75A"
backgroundColor = "#02070C"
secondaryBackgroundColor = "#07131D"
textColor = "#F7FAFC"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
