[theme]
base = "dark"
primaryColor = "#19D9FF"
backgroundColor = "#061426"
secondaryBackgroundColor = "#0B2038"
textColor = "#F5FAFF"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
